volumes:
  bitrix_taskmanager_redisdata:

services:
  bitrix_taskmanager_bot:
    build: .
    environment:
      BASE_BITRIX_WEBHOOK_URL: ${BASE_BITRIX_WEBHOOK_URL}
      BITRIX_TG_ID_FIELD: ${BITRIX_TG_ID_FIELD}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      REDIS_HOST: ${REDIS_HOST}
    entrypoint: bash -c "python main.py";
    depends_on:
      - bitrix_taskmanager_redis
    restart: always

  bitrix_taskmanager_authserver:
    build: .
    ports:
      - "${GUNICORN_PORT_FORWARD}:5000"
    environment:
      BASE_BITRIX_WEBHOOK_URL: ${BASE_BITRIX_WEBHOOK_URL}
      BITRIX_TG_ID_FIELD: ${BITRIX_TG_ID_FIELD}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      REDIS_HOST: ${REDIS_HOST}
    entrypoint: bash -c "gunicorn --bind 0.0.0.0:5000 web_server:app";
    restart: always

  bitrix_taskmanager_redis:
    image: redis:latest
    restart: always
    volumes:
      - bitrix_taskmanager_redisdata:/data
